pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat 'javac -encoding UTF-8 -d classes Practice/src/**/*.java'
            }
        }
		stage('Test') {
		    steps {
		        def classpath = "classes;lib/;C:\Users\eclipse\java-2024-03\eclipse\plugins\org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar"
		        bat 'java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
		    }
		}

    }
    post {
        always {
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
