pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat 'javac -encoding UTF-8 -d . Practice/src/Book.java Practice/src/BookManager.java Practice/src/PerformanceTest.java'
            }
        }
        stage('PerformanceTest') {
            steps {
                dir('Practice/src') {
                    bat 'java PerformanceTest > test_results.txt'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts 'Practice/src/test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}

